In [1]:
import pandas as pd
import numpy as np

# **Load Data**
---

In [2]:
df = pd.read_parquet('acs.parquet')

In [3]:
df.shape

(104259754, 18)

In [4]:
df.head()

,YEAR,STATEFIP,PERWT,SEX,AGE,RACE,RACED,HISPAN,HISPAND,EDUC,EDUCD,DEGFIELD,DEGFIELDD,EMPSTAT,EMPSTATD,WKSWORK1,UHRSWORK,INCWAGE
0,1950,23,37.0,1,36,1,100,0,0,0,0,<NA>,<NA>,1,10,0,<NA>,999999
1,1950,23,37.0,2,36,1,100,0,0,2,25,<NA>,<NA>,3,31,0,<NA>,0
2,1950,23,37.0,1,14,1,100,0,0,0,0,<NA>,<NA>,3,34,0,<NA>,999999
3,1950,23,37.0,2,12,1,100,0,0,0,0,<NA>,<NA>,0,0,0,<NA>,999999
4,1950,23,37.0,2,10,1,100,0,0,0,0,<NA>,<NA>,0,0,0,<NA>,999999

In [5]:
df.tail()

,YEAR,STATEFIP,PERWT,SEX,AGE,RACE,RACED,HISPAN,HISPAND,EDUC,EDUCD,DEGFIELD,DEGFIELDD,EMPSTAT,EMPSTATD,WKSWORK1,UHRSWORK,INCWAGE
104259749,2024,56,104.0,2,56,1,123,0,0,7,71,0,0,1,10,52,48,32000
104259750,2024,56,92.0,1,78,1,123,0,0,7,71,0,0,3,30,0,0,0
104259751,2024,56,74.0,2,74,1,123,0,0,6,65,0,0,3,30,0,0,0
104259752,2024,56,134.0,2,20,1,177,0,0,6,61,0,0,1,10,48,35,38500
104259753,2024,56,71.0,1,22,8,826,1,100,6,65,0,0,1,10,40,30,20000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104259754 entries, 0 to 104259753
Data columns (total 18 columns):
 #   Column     Dtype
---  ------     -----
 0   YEAR       Int64
 1   STATEFIP   Int64
 2   PERWT      float64
 3   SEX        Int64
 4   AGE        Int64
 5   RACE       Int64
 6   RACED      Int64
 7   HISPAN     Int64
 8   HISPAND    Int64
 9   EDUC       Int64
 10  EDUCD      Int64
 11  DEGFIELD   Int64
 12  DEGFIELDD  Int64
 13  EMPSTAT    Int64
 14  EMPSTATD   Int64
 15  WKSWORK1   Int64
 16  UHRSWORK   Int64
 17  INCWAGE    Int64
dtypes: Int64(17), float64(1)
memory usage: 15.6 GB

In [7]:
df.describe()

,YEAR,STATEFIP,PERWT,SEX,AGE,RACE,RACED,HISPAN,HISPAND,EDUC,EDUCD,DEGFIELD,DEGFIELDD,EMPSTAT,EMPSTATD,WKSWORK1,UHRSWORK,INCWAGE
count,104259754.0,104259754.0,1.042598e+08,104259754.0,104259754.0,104259754.0,104259754.0,104259754.0,104259754.0,104259754.0,104259754.0,50626224.0,50626224.0,104259754.0,104259754.0,58972162.0,91341564.0,104259754.0
mean,2000.60046,27.940952,8.416858e+01,1.512352,38.037909,1.702417,173.103996,0.206878,21.871396,5.396578,56.01063,10.35549,1036.923995,1.436751,14.418687,22.369957,19.863427,239162.680179
std,20.153458,15.760807,1.032491e+02,0.499847,23.407772,1.76844,180.731767,0.721901,78.69129,3.341557,33.297965,20.272278,2029.370918,1.136979,11.376918,24.224477,21.326655,408514.489242
min,1950.0,1.0,0.000000e+00,1.0,0.0,1.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,1990.0,13.0,2.000000e+01,1.0,18.0,1.0,100.0,0.0,0.0,2.0,25.0,0.0,0.0,1.0,10.0,0.0,0.0,0.0
50%,2008.0,28.0,5.900000e+01,2.0,37.0,1.0,100.0,0.0,0.0,6.0,62.0,0.0,0.0,1.0,10.0,3.0,10.0,15000.0
75%,2016.0,41.0,1.010000e+02,2.0,57.0,1.0,100.0,0.0,0.0,7.0,71.0,0.0,0.0,3.0,30.0,52.0,40.0,102000.0
max,2024.0,56.0,5.419000e+03,2.0,100.0,9.0,991.0,4.0,499.0,11.0,116.0,64.0,6403.0,3.0,34.0,52.0,99.0,999999.0

In [8]:
df = df.rename(columns = {"YEAR": "Year",
                          "STATEFIP": "State FIP Code",
                          "PERWT": "Individuals Represented",
                          "SEX": "Sex",
                          "AGE": "Age",
                          "RACE": "Race",
                          "RACED": "Race (Detailed)",
                          "HISPAN": "Hispanic",
                          "HISPAND": "Hispanic (Detailed)",
                          "EDUC": "Education Level",
                          "EDUCD": "Education Level (Detailed)",
                          "DEGFIELD": "Major",
                          "DEGFIELDD": "Major (Detailed)",
                          "EMPSTAT": "Employment Status",
                          "EMPSTATD": "Employment Status (Detailed)",
                          "WKSWORK1": "Weeks Worked",
                          "UHRSWORK": "Hours Worked",
                          "INCWAGE": "Income (Nominal)"})

# **Filter Data**
---

In [9]:
# Restrict to working-age individuals
df = df[(df['Age'] >= 25) & (df['Age'] <= 64)]

In [10]:
# Restrict to employed individuals
df = df[df['Employment Status'] == 1]

In [11]:
# Restrict to individuals with positive incomes below the confidentiality cap
df = df[(df['Income (Nominal)'] > 0) & (df['Income (Nominal)'] < 999999)]

In [12]:
# Restrict to full-time individuals 
df = df[(df['Weeks Worked'] >= 40) & (df['Hours Worked'] >= 35)]

In [13]:
# Remove years where hours worked don't exist
years_with_hours = (
    df.groupby("Year")["Hours Worked"]
      .apply(lambda x: x.notna().any())
)

years_with_hours = years_with_hours[years_with_hours].index

df = df[df["Year"].isin(years_with_hours)]

# **Map Data**
---

In [14]:
df["Sex"] = df["Sex"].map({1: "Male", 2: "Female"})

In [15]:
def clean_race(row):
    if row['Hispanic'] in [1,2,3,4]:
        return "Hispanic"
    
    if row['Race'] == 1:
        return "White"
    elif row['Race'] == 2:
        return "Black"
    elif row['Race'] in [4,5,6]:
        return "Asian"
    else:
        return "Other"

df['Demographic'] = df.apply(clean_race, axis=1)

In [16]:
major_map = {
    0: np.nan,
    11: "Agriculture",
    13: "Environment and Natural Resources",
    14: "Architecture",
    15: "Area/Ethnic/Civilization Studies",
    19: "Communications",
    20: "Communications Technologies",
    21: "Computer and Information Sciences",
    22: "Culinary and Cosmetology",
    23: "Education Administration and Teaching",
    24: "Engineering",
    25: "Engineering Technologies",
    26: "Foreign Languages",
    29: "Family and Consumer Sciences",
    32: "Law",
    33: "English/Literature",
    34: "Liberal Arts and Humanities",
    35: "Library Science",
    36: "Biology and Life Sciences",
    37: "Mathematics and Statistics",
    38: "Military Technologies",
    40: "Interdisciplinary Studies",
    41: "Parks/Recreation/Leisure",
    48: "Philosophy and Religious Studies",
    49: "Theology",
    50: "Physical Sciences",
    51: "Nuclear/Industrial Technology",
    52: "Psychology",
    53: "Criminal Justice",
    54: "Public Affairs and Social Work",
    55: "Social Sciences",
    56: "Construction Services",
    57: "Electrical and Mechanical Repair",
    58: "Precision Production and Industrial Arts",
    59: "Transportation Sciences",
    60: "Fine Arts",
    61: "Medical and Health Sciences",
    62: "Business",
    64: "History"
}

df['Major'] = df["Major"].map(major_map)

In [17]:
def collapse_edu(x):
    if x < 62:
        return "HS or Less"
    elif 62 <= x < 101:
        return "Some College"
    elif x == 101:
        return "Bachelor's"
    else:
        return "Masters or Doctorate"

df["Education Group"] = df["Education Level (Detailed)"].apply(collapse_edu)

In [18]:
# Map numeric FIPS state codes to state names
state_fips_map = {
    1: "Alabama",
    2: "Alaska",
    4: "Arizona",
    5: "Arkansas",
    6: "California",
    8: "Colorado",
    9: "Connecticut",
    10: "Delaware",
    11: "District of Columbia",
    12: "Florida",
    13: "Georgia",
    15: "Hawaii",
    16: "Idaho",
    17: "Illinois",
    18: "Indiana",
    19: "Iowa",
    20: "Kansas",
    21: "Kentucky",
    22: "Louisiana",
    23: "Maine",
    24: "Maryland",
    25: "Massachusetts",
    26: "Michigan",
    27: "Minnesota",
    28: "Mississippi",
    29: "Missouri",
    30: "Montana",
    31: "Nebraska",
    32: "Nevada",
    33: "New Hampshire",
    34: "New Jersey",
    35: "New Mexico",
    36: "New York",
    37: "North Carolina",
    38: "North Dakota",
    39: "Ohio",
    40: "Oklahoma",
    41: "Oregon",
    42: "Pennsylvania",
    44: "Rhode Island",
    45: "South Carolina",
    46: "South Dakota",
    47: "Tennessee",
    48: "Texas",
    49: "Utah",
    50: "Vermont",
    51: "Virginia",
    53: "Washington",
    54: "West Virginia",
    55: "Wisconsin",
    56: "Wyoming"
}

df["State"] = df["State FIP Code"].map(state_fips_map)

# **Convert Nominal Incomes**
---

In [19]:
cpi = pd.read_excel("CPI.xlsx", index_col="Year")
cpi.index = cpi.index.astype(int)

In [20]:
base_year = 2024
base_cpi = cpi.loc[base_year, "Annual Average CPI(-U)"]

cpi["adjustment_factor"] = base_cpi / cpi["Annual Average CPI(-U)"]

In [21]:
df = df.merge(
    cpi["adjustment_factor"],
    left_on="Year",
    right_index=True,
    how="left"
)

In [22]:
df["Income (2024 Dollars)"] = df["Income (Nominal)"] * df["adjustment_factor"]

In [23]:
df["Log Income"] = np.log(df["Income (2024 Dollars)"])

# **Final Dataframe**
---

In [24]:
df = df.reset_index(drop = True)

In [25]:
cat_cols = [
    "State",
    "Sex",
    "Demographic",
    "Education Group",
    "Major",
    "Education Level (Detailed)"
]

for col in cat_cols:
    df[col] = df[col].astype("category")

In [26]:
# Memory Optimizations
df["Year"] = df["Year"].astype("int16")
df["Individuals Represented"] = df["Individuals Represented"].astype("int32")
df["Age"] = df["Age"].astype("int8")
df["Hours Worked"] = df["Hours Worked"].astype("int8")
df["Weeks Worked"] = df["Weeks Worked"].astype("int8")
df["Income (Nominal)"] = df["Income (Nominal)"].astype("int32")
df["Income (2024 Dollars)"] = df["Income (2024 Dollars)"].astype("float32")
df["Log Income"] = df["Log Income"].astype("float32")
df["Education Level (Detailed)"] = df["Education Level (Detailed)"].astype("int16")

In [27]:
df = df.drop(columns = ['State FIP Code', 'Race', 'Race (Detailed)', 'Hispanic', 'Hispanic (Detailed)', 'adjustment_factor', 'Major (Detailed)', 'Employment Status', 'Employment Status (Detailed)', 'Education Level'])

In [28]:
df.shape

(15715097, 14)

In [29]:
df.head()

,Year,Individuals Represented,Sex,Age,Education Level (Detailed),Major,Weeks Worked,Hours Worked,Income (Nominal),Demographic,Education Group,State,Income (2024 Dollars),Log Income
0,1980,20,Male,50,112,NaN,52,38,25005,White,Masters or Doctorate,Alaska,95195.007812,11.463683
1,1980,20,Female,58,60,NaN,48,40,18005,White,HS or Less,Alaska,68545.734375,11.135257
2,1980,20,Male,59,70,NaN,50,50,3005,White,Some College,Alaska,11440.151367,9.344885
3,1980,20,Female,47,60,NaN,48,40,27605,White,HS or Less,Alaska,105093.304688,11.562604
4,1980,20,Female,55,80,NaN,52,40,16005,White,Some College,Alaska,60931.656250,11.017509

In [30]:
df.tail()

,Year,Individuals Represented,Sex,Age,Education Level (Detailed),Major,Weeks Worked,Hours Worked,Income (Nominal),Demographic,Education Group,State,Income (2024 Dollars),Log Income
15715092,2024,39,Male,52,64,NaN,52,84,80000,Hispanic,Some College,Wyoming,80000.0,11.289782
15715093,2024,59,Female,45,64,NaN,52,40,27200,Hispanic,Some College,Wyoming,27200.0,10.210972
15715094,2024,51,Female,59,114,Medical and Health Sciences,52,36,46000,White,Masters or Doctorate,Wyoming,46000.0,10.736397
15715095,2024,81,Male,60,114,Education Administration and Teaching,52,40,132000,White,Masters or Doctorate,Wyoming,132000.0,11.790557
15715096,2024,104,Female,56,71,NaN,52,48,32000,White,Some College,Wyoming,32000.0,10.373491

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15715097 entries, 0 to 15715096
Data columns (total 14 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Year                        int16
 1   Individuals Represented     int32
 2   Sex                         category
 3   Age                         int8
 4   Education Level (Detailed)  int16
 5   Major                       category
 6   Weeks Worked                int8
 7   Hours Worked                int8
 8   Income (Nominal)            int32
 9   Demographic                 category
 10  Education Group             category
 11  State                       category
 12  Income (2024 Dollars)       float32
 13  Log Income                  float32
dtypes: category(5), float32(2), int16(2), int32(2), int8(3)
memory usage: 419.6 MB

In [32]:
df.describe()

,Year,Individuals Represented,Age,Education Level (Detailed),Weeks Worked,Hours Worked,Income (Nominal),Income (2024 Dollars),Log Income
count,1.571510e+07,1.571510e+07,1.571510e+07,1.571510e+07,1.571510e+07,1.571510e+07,1.571510e+07,1.571510e+07,1.571510e+07
mean,2.003309e+03,9.006376e+01,4.256599e+01,7.787560e+01,5.122579e+01,4.381836e+01,5.088154e+04,7.886309e+04,1.102279e+01
std,1.588823e+01,1.256398e+02,1.085044e+01,2.430702e+01,2.369377e+00,8.075093e+00,6.057432e+04,7.229598e+04,8.086576e-01
min,1.980000e+03,0.000000e+00,2.500000e+01,2.000000e+00,4.000000e+01,3.500000e+01,1.000000e+00,2.400153e+00,8.755325e-01
25%,1.990000e+03,2.000000e+01,3.300000e+01,6.200000e+01,5.200000e+01,4.000000e+01,2.000000e+04,4.051476e+04,1.060942e+01
50%,2.005000e+03,5.400000e+01,4.200000e+01,7.100000e+01,5.200000e+01,4.000000e+01,3.500000e+04,6.108951e+04,1.102010e+01
75%,2.020000e+03,1.070000e+02,5.100000e+01,1.010000e+02,5.200000e+01,4.500000e+01,6.000000e+04,9.210841e+04,1.143072e+01
max,2.024000e+03,4.492000e+03,6.400000e+01,1.160000e+02,5.200000e+01,9.900000e+01,9.070000e+05,1.010329e+06,1.382579e+01

In [33]:
df.to_parquet("acs_cleaned.parquet", index=False)